kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: timwebster9/nginx-neptune
    dockerfile: neptune/nginx/Dockerfile
    context: neptune/nginx
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD