apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-dmrxt
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-xgq6s:m-5060341c21f8","addresses":["192.168.1.116"],"port":53,"protocol":"TCP","podName":"default:pi-hole-c99fd59df-ds2px","allNodes":false},{"nodeName":"c-xgq6s:m-5060341c21f8","addresses":["192.168.1.116"],"port":53,"protocol":"UDP","podName":"default:pi-hole-c99fd59df-ds2px","allNodes":false},{"nodeName":"c-xgq6s:m-5060341c21f8","addresses":["192.168.1.116"],"port":67,"protocol":"UDP","podName":"default:pi-hole-c99fd59df-ds2px","allNodes":false},{"nodeName":"c-xgq6s:m-5060341c21f8","addresses":["192.168.1.116"],"port":9000,"protocol":"TCP","podName":"default:pi-hole-c99fd59df-ds2px","allNodes":false},{"nodeName":"c-xgq6s:m-5060341c21f8","addresses":["192.168.1.116"],"port":9443,"protocol":"TCP","podName":"default:pi-hole-c99fd59df-ds2px","allNodes":false}]'
  creationTimestamp: 2019-03-02T10:58:05Z
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-pi-hole
  name: pi-hole
  namespace: default
  resourceVersion: "7228675"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/pi-hole
  uid: 0e41dd71-3cda-11e9-b8da-b8ac6f34f1b5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-pi-hole
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-03-02T10:58:05Z
        field.cattle.io/ports: '[[{"containerPort":53,"dnsName":"pi-hole-hostport","hostPort":53,"kind":"HostPort","name":"53tcp530","protocol":"TCP","sourcePort":53},{"containerPort":53,"dnsName":"pi-hole-hostport","hostPort":53,"kind":"HostPort","name":"53udp530","protocol":"UDP","sourcePort":53},{"containerPort":67,"dnsName":"pi-hole-hostport","hostPort":67,"kind":"HostPort","name":"67udp670","protocol":"UDP","sourcePort":67},{"containerPort":80,"dnsName":"pi-hole-hostport","hostPort":9000,"kind":"HostPort","name":"80tcp90000","protocol":"TCP","sourcePort":9000},{"containerPort":443,"dnsName":"pi-hole-hostport","hostPort":9443,"kind":"HostPort","name":"443tcp94430","protocol":"TCP","sourcePort":9443}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-pi-hole
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/London
        image: pihole/pihole:4.2.2-1
        imagePullPolicy: Always
        name: pi-hole
        ports:
        - containerPort: 53
          hostPort: 53
          name: 53tcp530
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          name: 53udp530
          protocol: UDP
        - containerPort: 67
          hostPort: 67
          name: 67udp670
          protocol: UDP
        - containerPort: 80
          hostPort: 9000
          name: 80tcp90000
          protocol: TCP
        - containerPort: 443
          hostPort: 9443
          name: 443tcp94430
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/pihole
          name: etc-pihole
        - mountPath: /etc/dnsmasq.d
          name: etc-dnsmasq
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1
          - 1.1.1.1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/pihole/etc-pihole
          type: ""
        name: etc-pihole
      - hostPath:
          path: /data/pihole/etc-dnsmasq.d
          type: ""
        name: etc-dnsmasq
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-02T10:58:05Z
    lastUpdateTime: 2019-03-02T10:58:05Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-02T10:58:05Z
    lastUpdateTime: 2019-03-02T10:58:09Z
    message: ReplicaSet "pi-hole-c99fd59df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
