version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  unbound:
    container_name: unbound
    image: timwebster9/unbound:1.0.0
    ports:
      - "8553:53/tcp"
      - "8553:53/udp"

