apiVersion: v1
kind: Namespace
metadata:
  name: unbound
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unbound
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: timwebster9/unbound:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: unbound
  namespace: unbound
spec:
  selector:
    app: unbound
  ports:
  - protocol: UDP
    port: 8553
    name: dnsudp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.1.142